# Радиус локального чата (в блоках)
local-chat-radius: 100

# Формат сообщения
message-format: "{prefix}{username-color}{displayname}{suffix}<dark_gray> »<reset> {message}"

# Настройки форматов
formats:
  # Формат для локального чата
  local: "<yellow>Ⓛ</yellow> {message}"
  # Формат для глобального чата
  global: "<green>Ⓖ</green> {message}"

# Подставлять команды, отправленные через [/command]
commands:
  enabled: true
  display-text: "<aqua>[<yellow>{command}<aqua>]<reset>"
  hover-text: "<yellow>Нажмите, чтобы использовать команду!"
  click-action: "SUGGEST_COMMAND"

# Кастомные заполнители
custom-placeholders:
  # Показать инвентарь
  inv:
    display-text: "<white>[<aqua>Инвентарь <white>%player_name%]<reset>"
    inventory-title: "Инвентарь %player_name%"
    hover-text: "<yellow>Нажмите чтобы посмотреть!"
    click-action: "SHOW_INV"

  # Показать эндер сундук
  ender:
    display-text: "<white>[<light_purple>Эндер-сундук <white>%player_name%]<reset>"
    inventory-title: "Эндер сундук %player_name%"
    hover-text: "<yellow>Нажмите чтобы посмотреть!"
    click-action: "SHOW_ENDER"

  # Показать предмет из руки
  item:
    display-text: "<white>[{item}]<reset>"
    inventory-title: "Предмет %player_name%"
    hover-text: "<yellow>Нажмите чтобы посмотреть!"
    click-action: "SHOW_ITEM"

  # Показать баланс денег
  money:
    display-text: "<white>[<green>Монеты <white>%player_name%]<reset>"
    hover-text: "<green>Монеты %player_name%: %coinsengine_balance_short_clean_money%"
    click-action: "SUGGEST_COMMAND"
    click-value: "/money pay %player_name% "

  # Показать баланс коинов
  coins:
    display-text: "<white>[<gold>Коины <white>%player_name%]<reset>"
    hover-text: "<gold>Коины %player_name%: %coinsengine_balance_short_clean_coins%"
    click-action: "SUGGEST_COMMAND"
    click-value: "/coins pay %player_name% "

  # Предметы на аукционе игрока
  ah:
    display-text: "<white>[<yellow>Товары на аукционе <white>%player_name%]<reset>"
    hover-text: "<yellow>Товары на аукционе %player_name%"
    click-action: "RUN_COMMAND"
    click-value: "/ah view %player_name%"

  # Предложить обмен
  trade:
    display-text: "<white>[<yellow>Предложить обмен <white>%player_name%]<reset>"
    hover-text: "<yellow>Предложить обменяться вещами с %player_name%"
    click-action: "RUN_COMMAND"
    click-value: "/trade %player_name%"

  # Игровое время
  gametime:
    display-text: "<aqua>Время в игре: %player_world_time_24%<reset>"

  # Позиция игрока
  pos:
    display-text: "<aqua>Моя позиция: <white>%player_world% <yellow>X:<white>%player_x% <yellow>Y:<white>%player_y% <yellow>Z:<white>%player_z%<reset>"

  # Пинг игрока
  ping:
    display-text: "<aqua>Мой пинг: <green>%player_ping% <gray>мс<reset>"

  # Сайт сервера
  site:
    display-text: "<white>[<bold>Сайт: </bold><gradient:#ffb618:#ff4e18>FlyAwayMaking</gradient>]<reset>"
    hover-text: "<yellow>Перейти на наш сайт!"
    click-action: "OPEN_URL"
    click-value: "https://mc.flyawaymaking.ru/"

  # Магазин сервера
  shop:
    display-text: "<white>[<bold>Магазин: </bold><gradient:#ffb618:#ff4e18>FlyAwayMaking</gradient>]<reset>"
    hover-text: "<yellow>Перейти в наш магазин"
    click-action: "OPEN_URL"
    click-value: "https://mc.flyawaymaking.ru/shop/"

  # Группа в ВК
  vk:
    display-text: "<white>[<bold>ВК: </bold><gradient:#ffb618:#ff4e18>FlyAwayMaking</gradient>]<reset>"
    hover-text: "<yellow>Перейти в нашу группу ВК"
    click-action: "OPEN_URL"
    click-value: "https://vk.com/flyawaymaking/"
